From: Stephane Bortzmeyer <bortzmeyer@gitoyen.net>
To: auto-dbm@ripe.net
Subject: MODIFY AS20766 
X-NCC-RegID: fr.gitoyen

-----BEGIN PGP SIGNED MESSAGE-----

aut-num:      AS20766
as-name:      GITOYEN-MAIN-AS
descr:        The main Autonomous System of Gitoyen (Paris, France).
admin-c:      SB4267-RIPE
admin-c:      FC2409-RIPE
admin-c:      PB401
tech-c:       GI1036-RIPE
notify:       noc@gitoyen.net
mnt-by:       Gitoyen-NCC
remarks:      --
remarks:      Open peering policy: just ask peering@gitoyen.net
remarks:      --
remarks:      Technical problems or questions: noc@gitoyen.net
remarks:      --
remarks:      Looking Glass: http://lookinglass.gitoyen.net/
remarks:      --
changed:      noc@gitoyen.net  20020123 
source:       RIPE
import:       from AS1299
              action pref=100;
              accept ANY
import:       from AS6461
              action pref=100;
              accept ANY
export:       to AS1299
              announce AS-GITOYEN
export:       to AS6461
              announce AS-GITOYEN
import:    from AS13049
     action pref=100;
     accept AS13049
export:    to AS13049
     announce AS-GITOYEN
import:    from AS8255
     action pref=100;
     accept AS8255
export:    to AS8255
     announce AS-GITOYEN
import:    from AS6771
     action pref=100;
     accept AS6771
export:    to AS6771
     announce AS-GITOYEN
import:    from AS5089
     action pref=100;
     accept AS5089
export:    to AS5089
     announce AS-GITOYEN
import:    from AS13193
     action pref=100;
     accept AS13193
export:    to AS13193
     announce AS-GITOYEN
import:    from AS12876
     action pref=100;
     accept AS12876
export:    to AS12876
     announce AS-GITOYEN
import:    from AS2200
     action pref=100;
     accept AS2200
export:    to AS2200
     announce AS-GITOYEN
import:    from AS5410
     action pref=100;
     accept AS5410
export:    to AS5410
     announce AS-GITOYEN
import:    from AS6830
     action pref=100;
     accept AS-CHELLO
export:    to AS6830
     announce AS-GITOYEN
import:    from AS6461
     action pref=100;
     accept AS6461
export:    to AS6461
     announce AS-GITOYEN
import:    from AS6805
     action pref=100;
     accept AS-MWAYS
export:    to AS6805
     announce AS-GITOYEN
import:    from AS3303
     action pref=100;
     accept AS3303
export:    to AS3303
     announce AS-GITOYEN
import:    from AS5631
     action pref=100;
     accept AS5631
export:    to AS5631
     announce AS-GITOYEN
import:    from AS5496
     action pref=100;
     accept AS5496
export:    to AS5496
     announce AS-GITOYEN
import:    from AS13299
     action pref=100;
     accept AS13299
export:    to AS13299
     announce AS-GITOYEN
import:    from AS4589
     action pref=100;
     accept AS-EASYNET
export:    to AS4589
     announce AS-GITOYEN
import:    from AS6675
     action pref=100;
     accept AS6675
export:    to AS6675
     announce AS-GITOYEN
import:    from AS12322
     action pref=100;
     accept AS12322
export:    to AS12322
     announce AS-GITOYEN
import:    from AS2486
     action pref=100;
     accept AS2486
export:    to AS2486
     announce AS-GITOYEN
import:    from AS8304
     action pref=100;
     accept AS8304
export:    to AS8304
     announce AS-GITOYEN
import:    from AS7176
     action pref=100;
     accept AS7176
export:    to AS7176
     announce AS-GITOYEN
import:    from AS8228
     action pref=100;
     accept AS8228
export:    to AS8228
     announce AS-GITOYEN
import:    from AS9193
     action pref=100;
     accept AS9193
export:    to AS9193
     announce AS-GITOYEN
import:    from AS12626
     action pref=100;
     accept AS12626
export:    to AS12626
     announce AS-GITOYEN
import:    from AS8332
     action pref=100;
     accept AS8332
export:    to AS8332
     announce AS-GITOYEN
import:    from AS1899
     action pref=100;
     accept AS1899
export:    to AS1899
     announce AS-GITOYEN
import:    from AS12654
     action pref=100;
     accept AS12654
export:    to AS12654
     announce AS-GITOYEN
import:    from AS6678
     action pref=100;
     accept AS6678
export:    to AS6678
     announce AS-GITOYEN


-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.0.6 (GNU/Linux)
Comment: For info see http://www.gnupg.org

iQCVAwUBPE8hO4JORsNuyaVdAQEyCQQAq/baXaL3ypKW2E1zjXWctGs61SgPWfWr
HXDX3+m0QWWWtgnFoCgJbVVuVj6fbDYYBrTmiEIY6kAFDKmQhKDI6603XkDI5AEA
2WwDjvrBog+5OG4eMOQYoX5ylwy4v7KlaJBFUsYvhLD2nIhypqufVZx/rcNx3nmX
yHpBQQq4sLA=
=slkU
-----END PGP SIGNATURE-----
